project:
  type: website
  output-dir: docs

website:
  title: "Sangsuk Yoon"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
    right:
      - icon: envelope
        href: "mailto:syoon1@udayton.edu"
      - icon: github
        href: "https://github.com/ssyoon"
      - icon: twitter
        href: "https://twitter.com/mind314"
      # - icon: person-badge
      #   href: "https://orcid.org/0000-0002-3399-1096"

format:
  html:
    theme: simple
    css: styles.css
    toc: true

editor: visual