<br>

### Publications
- Venkatraman, V. & **Yoon, S.** "Adaptivity in decision-making strategies across age: Process insights and implications" Journal of Marketing Behavior (in press) 

- Botvinik-Nezer, R., Holzmeister, F., ..., Yoon, S., ..., & Schonberg, T. "The robustness of anchoring effects on preferential judgments." Nature (2020) [[Link]](https://www.nature.com/articles/s41586-020-2314-9)

- **Yoon, S.**, Fong, N., & Dimoka, A. "The robustness of anchoring effects on preferential judgments." Judgment and Decision Making (2019) [[Link]](http://www.sjdm.org/journal/19/190426/jdm190426.pdf)

- **Yoon, S.**, & Fong, N. "Uninformative anchors have persistent effects on valuation judgments." Journal of Consumer Psychology (2019) [[Link]](https://www.researchgate.net/publication/330469173_Uninformative_Anchors_Have_Persistent_Effects_on_Valuation_Judgments)

- Silberzahn, R., Uhlmann, E. L., Martin, D. P., Anselmi, P., ... **Yoon, S.**, & Nosek, B. A. "Many analysts, one data set: Making transparent how variations in analytic choices affect results." Advances in Methods and Practices in Psychological Science (2018) [[Link]](https://journals.sagepub.com/doi/abs/10.1177/2515245917747646)

- **Yoon, S.**, Vo, K., & Venkatraman, V. "Variability in Decision Strategies Across Description‐based and Experience‐based Decision Making." Journal of Behavioral Decision Making (2017) [[Link]](https://onlinelibrary.wiley.com/doi/abs/10.1002/bdm.2009)

- Choi, M., **Yoon, S.**, & Oh, J. "Development and Validation of the Korean Illness Perception Questionnaire (K-IPQ)." Health Communication (2016) [[Link]](http://www.papersearch.net/thesis/article.asp?key=3490215)

- Uehara, T., Li, B., Kim, BM., **Yoon, S. S.**, Quach, QK., Kim, H., & Chon. TS. "Inferring conflicting behavior of zebrafish (Danio rerio) in response to food and predator based on a self-organizing map (SOM) and intermittency test." Ecological Informatics (2015) [[Link]](https://www.sciencedirect.com/science/article/pii/S1574954114001411)

- **Yoon, S.**, & Shin, H. J. "The Effect of Substitute on WTA and WTP." The Korean Journal of Cognitive and Biological Psychology (2010)