---
title: "Sangsuk Yoon"
---


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-141187239-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-141187239-1');
</script>


<br> 

I am an Associate Professor of Marketing at University of Dayton. I'm studying cognitive biases underlying human decision making, and seek to apply findings from laboratory studies in judgment and decision making to consumer behavior (e.g., consumer preference, financial decision making, advertisement, and risk communications). I am also interested in using a multi-methodological approach, including behavioral, computational modeling, eye-tracking and fMRI, to obtain converging evidence about the underlying mechanisms of decision biases.


<br><br>

### Publications
- **Yoon, S.** & Venkatraman, V. "Choosing versus rejecting: The effect of decision mode on subsequent preferential choices" Journal of Behavioral Decision Making (2025) [[PDF]](./publications/2025_JBDM.pdf) | [[Journal]](https://onlinelibrary.wiley.com/doi/10.1002/bdm.70032)

- Dugan, R., Edelblum, A., Kalra, A., Lee, N. Y., & **Yoon, S**. "How social media and flexible work arrangements harden salespeople to abusive supervision" Industrial Marketing Management (2024) [[PDF]](./publications/2024_IMM.pdf) | [[Journal]](https://www.sciencedirect.com/science/article/abs/pii/S0019850124001160)

- **The Forecasting Collaborative**. "Insights into the accuracy of social scientists’ forecasts of societal change" Nature Human Behavior (2023) [[PDF]](./publications/2023_NHB.pdf) | [[Journal]](https://www.nature.com/articles/s41562-022-01517-1)

- Chae, B., **Yoon, S.**, Baskin, E., & Zhu. R. "The lasting smell of temptation: Counteractive effects of indulgent food scents" Journal of Business Research (2023) [[PDF]](./publications/2023_JBR.pdf) | [[Journal]](https://www.sciencedirect.com/science/article/abs/pii/S014829632200902X)

- Bago, B., Kovacs, M., ..., **Yoon, S.**, ..., & Aczel, B. "Situational factors shape moral judgments in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample" Nature Human Behavior (2022) [[PDF]](./publications/2022_NHB.pdf) | [[Journal]](https://www.nature.com/articles/s41562-022-01319-5)

- Choi, M. & **Yoon, S.** "Asymmetric underlying mechanisms of relation-based and property-based noun-noun conceptual combination" Frontiers in Psychology: Cognition (2021) [[PDF]](./publications/2021_Frontiers.pdf) | [[Journal]](https://www.frontiersin.org/articles/10.3389/fpsyg.2021.567971/abstract)

- Venkatraman, V. & **Yoon, S.** "Adaptivity in decision-making strategies across age: Process insights and implications" Journal of Marketing Behavior (2020) [[PDF]](./publications/2020_JMB.pdf) | [[Journal]](https://www.nowpublishers.com/article/Details/JMB-0067)

- Botvinik-Nezer, R., Holzmeister, F., ..., **Yoon, S.**, ..., & Schonberg, T. "Variability in the analysis of a single neuroimaging dataset by many teams." Nature (2020) [[PDF]](./publications/2020_Nature.pdf) | [[Journal]](https://www.nature.com/articles/s41586-020-2314-9)

- **Yoon, S.**, Fong, N., & Dimoka, A. "The robustness of anchoring effects on preferential judgments." Judgment and Decision Making (2019) [[PDF]](./publications/2019_JDM.pdf) | [[Journal]](http://www.sjdm.org/journal/19/190426/jdm190426.pdf)

- **Yoon, S.**, & Fong, N. "Uninformative anchors have persistent effects on valuation judgments." Journal of Consumer Psychology (2019) [[PDF]](./publications/2019_JCP.pdf) | [[Journal]](https://www.researchgate.net/publication/330469173_Uninformative_Anchors_Have_Persistent_Effects_on_Valuation_Judgments)

- Silberzahn, R., Uhlmann, E. L., Martin, D. P., Anselmi, P., ... **Yoon, S.**, & Nosek, B. A. "Many analysts, one data set: Making transparent how variations in analytic choices affect results." Advances in Methods and Practices in Psychological Science (2018) [[PDF]](./publications/2018_AMPPS.pdf) | [[Journal]](https://journals.sagepub.com/doi/abs/10.1177/2515245917747646)

- **Yoon, S.**, Vo, K., & Venkatraman, V. "Variability in Decision Strategies Across Description‐based and Experience‐based Decision Making." Journal of Behavioral Decision Making (2017) [[PDF]](./publications/2017_JBDM.pdf) | [[Journal]](https://onlinelibrary.wiley.com/doi/abs/10.1002/bdm.2009)

- Choi, M., **Yoon, S.**, & Oh, J. "Development and Validation of the Korean Illness Perception Questionnaire (K-IPQ)." Health Communication (2016) [[PDF]](./publications/2016_KJHC.pdf) | [[Journal]](http://www.papersearch.net/thesis/article.asp?key=3490215)

- Uehara, T., Li, B., Kim, BM., **Yoon, S. S.**, Quach, QK., Kim, H., & Chon. TS. "Inferring conflicting behavior of zebrafish (Danio rerio) in response to food and predator based on a self-organizing map (SOM) and intermittency test." Ecological Informatics (2015) [[PDF]](./publications/2015_EI.pdf) | [[Journal]](https://www.sciencedirect.com/science/article/pii/S1574954114001411)

- **Yoon, S.**, & Shin, H. J. "The Effect of Substitute on WTA and WTP." The Korean Journal of Cognitive and Biological Psychology (2010) [[PDF]](./publications/2010_KJCBP.pdf) |