---
title: ""
---

<!-- Global site tag (gtag.js) - Google Analytics -->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-141187239-1"></script>
```

```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-141187239-1');
</script>
```

**Welcome!**

I am an Associate Professor of Marketing at University of Dayton. My research examines the cognitive biases underlying human decision making, with a focus on how these biases shape consumer behavior in real-world contexts.

I study how findings from laboratory studies in judgment and decision making apply to various consumer decisions, including consumer preferential choices, financial decision making, and risk communications. My work bridges cognitive psychology and consumer behavior to understand not just what decisions people make, but why they make them.

I am also interested in using a multi-methodological approach, including behavioral, computational modeling, eye-tracking, and fMRI, to obtain converging evidence about the underlying mechanisms of cognitive biases and decision making processes. 


#### Work Experience
- Associate Professor, University of Dayton, 2025 - Present
- Assistant Professor, University of Dayton, 2018 - 2025
- Graduate Research Assistant, [Center for Applied Research in Decision Making (CARD)](https://www.fox.temple.edu/faculty-research/institutes-centers/center-applied-research-decision-making), Temple University, 2012 - 2018
- Research Assistant, Ecology and Behavior System Lab, Pusan National University, 2011
- Research Assistant, Cognition Lab, Pusan National University, 2009-2010


#### Education 

- Ph.D. in Business Administration (Interdisciplinary Studies - Marketing), Temple University, 2018
- MA. in Psychology (Cognitive), Pusan National University, 2011
- BBA. in Business Administration & BA. in Psychology, Pusan National University, 2006



#### Working Papers
-   Bahník, Š. & **Yoon, S.** "Anchoring effect in business" [\[PDF\]](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=SlY_MUwAAAAJ&sortby=pubdate&citation_for_view=SlY_MUwAAAAJ:HDshCWvjkbEC)

-   **Yoon, S.** & Fong, N. "Incongruent Effects of Anchoring on Valuation and Choice" [\[PDF\]](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=SlY_MUwAAAAJ&sortby=pubdate&citation_for_view=SlY_MUwAAAAJ:-f6ydRqryjwC)



#### Publications

-   **Yoon, S.** & Venkatraman, V. "Choosing versus rejecting: The effect of decision mode on subsequent preferential choices" *Journal of Behavioral Decision Making* (2025) [\[PDF\]](./publications/2025_JBDM.pdf) \| [\[OSF\]](https://osf.io/4nqws/) \| [\[Journal\]](https://onlinelibrary.wiley.com/doi/10.1002/bdm.70032)

-   Dugan, R., Edelblum, A., Kalra, A., Lee, N. Y., & **Yoon, S**. "How social media and flexible work arrangements harden salespeople to abusive supervision" *Industrial Marketing Management* (2024) [\[PDF\]](./publications/2024_IMM.pdf) \| [\[Journal\]](https://www.sciencedirect.com/science/article/abs/pii/S0019850124001160)

-   **The Forecasting Collaborative**. "Insights into the accuracy of social scientists’ forecasts of societal change" *Nature Human Behavior* (2023) [\[PDF\]](./publications/2023_NHB.pdf) \| [\[Journal\]](https://www.nature.com/articles/s41562-022-01517-1)

-   Chae, B., **Yoon, S.**, Baskin, E., & Zhu. R. "The lasting smell of temptation: Counteractive effects of indulgent food scents" *Journal of Business Research* (2023) [\[PDF\]](./publications/2023_JBR.pdf) \| [\[OSF\]](https://osf.io/yxfpj/) \| [\[Journal\]](https://www.sciencedirect.com/science/article/abs/pii/S014829632200902X)

-   Bago, B., Kovacs, M., ..., **Yoon, S.**, ..., & Aczel, B. "Situational factors shape moral judgments in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample" *Nature Human Behavior* (2022) [\[PDF\]](./publications/2022_NHB.pdf) \| [\[Journal\]](https://www.nature.com/articles/s41562-022-01319-5)

-   Choi, M. & **Yoon, S.** "Asymmetric underlying mechanisms of relation-based and property-based noun-noun conceptual combination" *Frontiers in Psychology: Cognition* (2021) [\[PDF\]](./publications/2021_Frontiers.pdf) \| [\[OSF\]](https://osf.io/t5p8a/) \| [\[Journal\]](https://www.frontiersin.org/articles/10.3389/fpsyg.2021.567971/abstract)

-   Venkatraman, V. & **Yoon, S.** "Adaptivity in decision-making strategies across age: Process insights and implications" *Journal of Marketing Behavior* (2020) [\[PDF\]](./publications/2020_JMB.pdf) \| [\[Journal\]](https://www.nowpublishers.com/article/Details/JMB-0067)

-   Botvinik-Nezer, R., Holzmeister, F., ..., **Yoon, S.**, ..., & Schonberg, T. "Variability in the analysis of a single neuroimaging dataset by many teams." *Nature* (2020) [\[PDF\]](./publications/2020_Nature.pdf) \| [\[Journal\]](https://www.nature.com/articles/s41586-020-2314-9)

-   **Yoon, S.**, Fong, N., & Dimoka, A. "The robustness of anchoring effects on preferential judgments." *Judgment and Decision Making* (2019) [\[PDF\]](./publications/2019_JDM.pdf) \| [\[OSF\]](https://osf.io/u2x7j/) \| [\[Journal\]](http://www.sjdm.org/journal/19/190426/jdm190426.pdf)

-   **Yoon, S.**, & Fong, N. "Uninformative anchors have persistent effects on valuation judgments." *Journal of Consumer Psychology* (2019) [\[PDF\]](./publications/2019_JCP.pdf) \| [\[OSF\]](https://osf.io/e2byg/) \| [\[Journal\]](https://www.researchgate.net/publication/330469173_Uninformative_Anchors_Have_Persistent_Effects_on_Valuation_Judgments)

-   Silberzahn, R., Uhlmann, E. L., Martin, D. P., Anselmi, P., ... **Yoon, S.**, & Nosek, B. A. "Many analysts, one data set: Making transparent how variations in analytic choices affect results." *Advances in Methods and Practices in Psychological Science* (2018) [\[PDF\]](./publications/2018_AMPPS.pdf) \| [\[Journal\]](https://journals.sagepub.com/doi/abs/10.1177/2515245917747646)

-   **Yoon, S.**, Vo, K., & Venkatraman, V. "Variability in Decision Strategies Across Description‐based and Experience‐based Decision Making." *Journal of Behavioral Decision Making* (2017) [\[PDF\]](./publications/2017_JBDM.pdf) \| [\[Journal\]](https://onlinelibrary.wiley.com/doi/abs/10.1002/bdm.2009)

-   Choi, M., **Yoon, S.**, & Oh, J. "Development and Validation of the Korean Illness Perception Questionnaire (K-IPQ)." *Health Communication* (2016; in Korean) [\[PDF\]](./publications/2016_KJHC.pdf) \| [\[Journal\]](http://www.papersearch.net/thesis/article.asp?key=3490215)

    -   [*한국어: "한국판 질병지각검사 (K-IPQ) 의 개발 및 타당화." 의료커뮤니케이션 11(2), 123-143, 2016*]{style="font-size: 0.9em;"}

-   Uehara, T., Li, B., Kim, BM., **Yoon, S. S.**, Quach, QK., Kim, H., & Chon. TS. "Inferring conflicting behavior of zebrafish (Danio rerio) in response to food and predator based on a self-organizing map (SOM) and intermittency test." *Ecological Informatics* (2015) [\[PDF\]](./publications/2015_EI.pdf) \| [\[Journal\]](https://www.sciencedirect.com/science/article/pii/S1574954114001411)

-   **Yoon, S.**, & Shin, H. J. "The Effect of Substitute on WTA and WTP." *The Korean Journal of Cognitive and Biological Psychology* (2010; in Korean) [\[PDF\]](./publications/2010_KJCBP.pdf)

    -   [*한국어: "대체재의 가용 여부가 WTA와 WTP에 미치는 영향." 한국심리학회: 인지 및 생물 22(4), 601-619, 2010*]{style="font-size: 0.9em;"}
